orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  start-server:
    docker:
      - image: cypress/base:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Start the server
          command: npm start &
      - run:
          name: Wait for server to be ready
          command: npx wait-on http://localhost:3001
      - run:
          name: Build the app
          command: npm run build

workflows:
  run-tests-and-deploy-to-staging-hold-then-production:
    jobs:
      - start-server
      - cypress/run:
          name: run-component-tests
          cypress-command: npx cypress run --component
          requires:
            - start-server
      - deploy-to-render-staging:
          requires:
            - run-component-tests
          filters:
            branches:
              only: main
      - hold:
          type: approval
          requires:
            - deploy-to-render-staging
      - deploy-to-render-production:
          requires:
            - hold
          filters:
            branches:
              only: main